CREATE SEQUENCE IF NOT EXISTS seq_con;

CREATE OR REPLACE FUNCTION FUN_TG_SEQ_CON()
RETURNS "trigger" AS
$BODY$
	BEGIN
		NEW.con_id := nextval('seq_con');
		Return NEW;
	END;
$BODY$
LANGUAGE 'plpgsql' VOLATILE;

CREATE TRIGGER TG_SEQ_CON
BEFORE INSERT ON CONTATOS
FOR EACH ROW
EXECUTE PROCEDURE FUN_TG_SEQ_CON();