spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  datasource:
    name: test_db
    password: ''
    driver-class-name: org.h2.Driver
    username: sa
    url: jdbc:h2:file:./data/test_db;INIT=create schema if not exists test_db;DB_CLOSE_ON_EXIT=TRUE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;
    initialize: false
  h2:
    console:
      path: /h2
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
server:
  servlet:
    context-path: /api
  port: '9999'
