spring:
  main:
    allow-bean-definition-overriding: true
    banner-mode: 'off'
  datasource:
     driverClassName: org.postgresql.Driver
     username: postgres
     password: temperosoft_psql
     url: jdbc:postgresql://localhost:5432/scm-fornecedores
server:
  servlet:
    context-path: /api
  port: '9999'
